PageHandlerExamples/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PageHandlerExamples.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

PageHandlerExamples/Pages/PageHandlerTest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PageHandlerExamples.Pages
{
    public class PageHandlerTestModel : PageModel
    {
        [BindProperty]
        public string Text { get; set; }
        public string Message { get; set; }
        public string SubmitButtonValue { get; set; }
        public string PageHandler { get; set; }
        public string PostMessage { get; set; }
        public void OnGet()
        {
            Message = "Kald via OnGet";
            SubmitButtonValue = "Gem tekst";
            PageHandler = "";
        }

        public void OnPost()
        {
            PostMessage = $"OnPost med teksten: {Text}";
        }

        public void OnGetEdit()
        {
            Message = "Kald via OnGetEdit";
            SubmitButtonValue = "Opdater tekst";
            PageHandler = "Edit";
        }

        public void OnPostEdit()
        {
            PostMessage = $"OnPostEdit med teksten: {Text}";
        }

    }
}

PageHandlerExamples/Pages/Index.cshtml
@page
@model PageHandlerExamples.Pages.IndexModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <ul>
        <li><a asp-page="PageHandlerTest">Dette er et get kald til PageHandlerTest uden en handler</a></li>
        <li><a asp-page="PageHandlerTest" asp-page-handler="Edit">Dette er et get kald til PageHandlerTest med en handler kaldet Edit</a></li>
        <li><a asp-page="PageHandlerTest" asp-page-handler="Delete">Dette er et get kald til PageHandlerTest med en handler der ikke findes</a></li>
    </ul>
</body>
</html>

PageHandlerExamples/Pages/PageHandlerTest.cshtml
@page
@model PageHandlerExamples.Pages.PageHandlerTestModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PageHandlerTest</title>
</head>
<body>
    <h1>@Model.Message</h1>
    <form method="post" asp-page="PageHandlerTest" asp-page-handler="@Model.PageHandler">
        <label asp-for="Text"></label>
        <input asp-for="Text" />
        <input type="submit" value="@Model.SubmitButtonValue" />
    </form>
    <div>
        <h2>@Model.PostMessage</h2>
    </div>
</body>
</html>